name: phone_pe_pg
description: A new Flutter plugin project.
version: 0.0.1
homepage: https://hassanansari.dev/

environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: ">=3.3.0"

dependencies:
  crypto: ^3.0.3
  dio: ^5.3.0
  flutter:
    sdk: flutter
  flutter_inappwebview: ^5.7.2+3
  plugin_platform_interface: ^2.0.2
  provider: ^6.0.5
  url_launcher: ^6.1.12

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.0.0+1


flutter:
  plugin:
    platforms:
      android:
        package: dev.hassanansari.phone_pe_pg
        pluginClass: PhonePePgPlugin
      ios:
        pluginClass: PhonePePgPlugin
