name: phone_pe_pg
description: >-
  A Flutter plugin for integrating PhonePe Payment Gateway in flutter, with support for Android and iOS (currently).
version: 0.0.4
homepage: https://hassanansari.dev/
repository: https://github.com/incrediblezayed/phone_pe_pg

environment:
  sdk: ">=3.0.5 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  crypto: ^3.0.3
  dio: ^5.3.2
  flutter:
    sdk: flutter
  flutter_inappwebview: ^5.7.2+3
  plugin_platform_interface: ^2.1.5
  provider: ^6.0.5
  url_launcher: ^6.1.12

dev_dependencies:
  flutter_lints: ^2.0.3
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.0.0+1

flutter:
  plugin:
    platforms:
      android:
        package: dev.hassanansari.phone_pe_pg
        pluginClass: PhonePePgPlugin
      ios:
        pluginClass: PhonePePgPlugin
