name: phone_pe_pg
description: >-
  A Flutter plugin for integrating PhonePe Payment Gateway in flutter, with support for Android and iOS (currently).
version: 0.0.7
homepage: https://hassanansari.dev/
repository: https://github.com/incrediblezayed/phone_pe_pg

environment:
  sdk: ">=3.0.5 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  crypto: ^3.0.3
  dio: ^5.4.1
  flutter:
    sdk: flutter
  flutter_inappwebview: ^6.0.0
  plugin_platform_interface: ^2.1.8
  provider: ^6.1.1
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: dev.hassanansari.phone_pe_pg
        pluginClass: PhonePePgPlugin
      ios:
        pluginClass: PhonePePgPlugin
